### ISSUE TITLE
Tracking issue for constant folding

### ISSUE THREAD

**Issue by lachlansneff** [CraneStation/cranelift#554]
This is the tracking issue for minimal constant-folding support. The aim is to collapse code like
```clif
v0 = iconst.i32 5
v1 = iconst.i32 37
v2 = iadd v1, v0
```
into
```clif
v2 = iconst.i32 42
```

and

```clif
ebb0:
  v0 = bconst true
  brnz v0, ebb1
  ...
ebb1
  ...
```
into
```clif
ebb0:
  jump ebb1
  ...
ebb1
  ...
```

Progress:

- [ ] Add constant folding pass

- [ ] Collapse simple operations on constants.

- [ ] Collapse branches when branch can be determined at compile time.
